name: doctor_love
description: An AI-powered chat analyzer that helps you understand interest levels in conversations using Google Gemini.
publish_to: "none"
version: 3.5.7+11

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_generative_ai: ^0.4.0
  image_picker: ^1.0.7
  flutter_animate: ^4.5.0
  google_fonts: ^6.1.0
  flutter_overlay_window: any
  permission_handler: ^11.3.1
  path_provider: ^2.1.5
  envied: ^0.5.4
  http: ^1.2.0
  shared_preferences: ^2.2.2
  image: ^4.2.0
  device_screenshot:
    path: packages/device_screenshot
  flutter_markdown: ^0.6.19
  uuid: ^4.3.3
  # Firebase
  firebase_core: ^2.24.2
  firebase_remote_config: ^4.3.8
  # Menu features
  flutter_secure_storage: ^9.0.0
  share_plus: ^7.2.1
  in_app_review: ^2.0.8
  url_launcher: ^6.2.1
  package_info_plus: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.2
  envied_generator: ^0.5.4
  build_runner: ^2.4.8

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon.png"

flutter:
  uses-material-design: true
